# PostgreSQL datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/horserace_db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Disable H2 Console
spring.h2.console.enabled=false